// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeyqX1O_r2ADIyU752sJZsxuR1qO3pT7U',
    appId: '1:690529205411:web:c811a442545f7e1a37d316',
    messagingSenderId: '690529205411',
    projectId: 'ranwall-611f6',
    authDomain: 'ranwall-611f6.firebaseapp.com',
    storageBucket: 'ranwall-611f6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-lEgfiFh-X3Rh2M_nqv_stnE_97r1dok',
    appId: '1:690529205411:android:1493bdd41ca92bd137d316',
    messagingSenderId: '690529205411',
    projectId: 'ranwall-611f6',
    storageBucket: 'ranwall-611f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6QpH5gkTqIdlJbIwl6Gdvs2wPP7LoJkQ',
    appId: '1:690529205411:ios:2089e0170fa9cd2237d316',
    messagingSenderId: '690529205411',
    projectId: 'ranwall-611f6',
    storageBucket: 'ranwall-611f6.appspot.com',
    iosClientId: '690529205411-09ou6rsr4o11l5pt07ecjmn3i947g7ff.apps.googleusercontent.com',
    iosBundleId: 'com.example.theWall',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6QpH5gkTqIdlJbIwl6Gdvs2wPP7LoJkQ',
    appId: '1:690529205411:ios:2089e0170fa9cd2237d316',
    messagingSenderId: '690529205411',
    projectId: 'ranwall-611f6',
    storageBucket: 'ranwall-611f6.appspot.com',
    iosClientId: '690529205411-09ou6rsr4o11l5pt07ecjmn3i947g7ff.apps.googleusercontent.com',
    iosBundleId: 'com.example.theWall',
  );
}
